# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_ghqc_wrappers", use_symbols = TRUE, package_name = "ghqc")

#' @usage NULL
#' @useDynLib ghqc, .registration = TRUE
NULL

run <- function(port, directory) .Call(wrap__run, port, directory)


# nolint end
